#!/bin/bash

#------------------------------------------------------------------------------
# Wait for the network:
#------------------------------------------------------------------------------

[ "${WAIT_NETWORK}" ] && {

  RETRIES=20

  echo '[Init] Waiting for the network...'

  while [ ${RETRIES} -gt 0 ]; do
    ip r 2> /dev/null | grep -q default && break
    sleep 1; RETRIES=$((RETRIES - 1))
  done

  [ ${RETRIES} -eq 0 ] && {
    echo '[Init] There is no network'
    exit 1
  }

  echo '[Init] A default gateway is present'
}

#------------------------------------------------------------------------------
# Configure the service:
#------------------------------------------------------------------------------

echo '[Init] Configuring the service...'
export DOCKER_REGISTRY_CONFIG='/etc/docker-registry.yml'
export SETTINGS_FLAVOR='local'

#------------------------------------------------------------------------------
# Run:
#------------------------------------------------------------------------------

echo "[Init] Executing: $*"
cd /usr/lib/python2.7/site-packages/docker-registry
exec $*
